### PR TITLE
Add member dns name support in runners

### PR DESCRIPTION
**Pull request by segabriel**

### CODE REVIEW

**Comment by artem-v** [comment]
Cody complains to avoid `Avoid unnecessary constructors `   in runner classes. Not to say that I agree with it, but plz make Codacy thing happy.

**Comment by segabriel** [comment]
@artem-v yeah, of course, but how you can see here https://github.com/scalecube/scalecube-gateway/pull/159/files#diff-b6211dd6631647f67b94be66c708fdc4L60 I've already removed it, it's a very old codacy message, it has a lag.

**Comment by artem-v** [comment]
@segabriel  You know what, I will make release of scalecube-services with that cool fixes with normal api for setting up discovery config with consumer and builder, really, nice stuff. Let's wait a bit here and then integrate new api from right here.

**Comment by artem-v** [comment]
Have just merged https://github.com/scalecube/scalecube-services/pull/355 --  watch out for new release

**Comment by segabriel** [comment]
@artem-v done

**Pull request merged**
